### PR TITLE
Path should contain the query string

### PR DESCRIPTION
**Pull request by sebinsua**
Relates to: https://github.com/economist-components/component-win-app/pull/42

### CODE REVIEW

**Comment by sebinsua** [comment]
@danielmoll See also.

**Comment by keithamus** [comment]
What ramifications does this have btw? Presumably the qs was stripped before for a good reason?

**Comment by fabiosantoscode** [comment]
The actual fix here would be to add `search` to the URL as well. The parser is there for a reason. You can't trust `req.url` to start with the slash. Proxies usually send the full URL instead.

**Comment by fabiosantoscode** [comment]
Or to use `path` instead of `pathname`. The former also includes the query string.

**Comment by sebinsua** [comment]
@keithamus I [need the query to be passed to the component-win-app for navigation to open/close itself without client-side JavaScript](https://github.com/economist-components/component-win-app/pull/42)

@fabiosantoscode Good point. Will fix.

**Comment by sebinsua** [comment]
@keithamus @fabiosantoscode Done.

**Pull request closed without merging**
